build:
	docker compose build

start:
	docker compose up -d

stop:
	docker compose stop

restart:
	docker compose restart

down:
	docker compose down

logs:
	docker compose logs -f

shell:
	docker compose exec frontend bash