version: "3"

volumes:
  node_modules:
services:
  frontend:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/frontend/node_modules

